camera:
  ros__parameters:
    lifecycle_activation_delay: 4.0  # Delay in seconds between configure and activate
    image_degradation: 0.0
    image_mean_threshold: 25.0 # threshold for the necessary image shift to be considered degraded
    camera_driver_issue: False
    hardware_disconnect: False
    autofocus_needed: False
    perform_autofocus: False

depth:
  ros__parameters:
    lifecycle_activation_delay: 4.0  # Should be the same as camera
    depth_degradation: 0.0
    do_drop_depth_camera: False

sensor_fusion:
  ros__parameters:
    lifecycle_activation_delay: 2.0  # Delay in seconds between configure and activate
    topic_camera_input: "rgb_camera"
    modality: 0  # 0=fusion
    delta_t_threshold: 0.01 # max time difference between synchronous frames
    image_shift: 0
    do_recalibration: False
    sync_issue: False
    memory_leakage: False
    
image_enhancement:
  ros__parameters:
    image_degradation: 1.5
    
segmentation:
  ros__parameters:
    lifecycle_activation_delay: 2.0  # Delay in seconds between configure and activate
    cuda_out_of_memory: False
    gpu_failure: False
    
blackboard_setter:
  ros__parameters:
    